### ISSUE TITLE
Saved the wrong plugin

### ISSUE THREAD

**Issue by intergrav** [Dinnyesensei/OfficalStyleScriptGuide#2]
Seems like you accidentally overwrote over it with your DataStore plugin.
![image](https://user-images.githubusercontent.com/42325132/111252144-df48e200-85e6-11eb-820c-d386a401cb6e.png)
![image](https://user-images.githubusercontent.com/42325132/111252157-e374ff80-85e6-11eb-95a8-1ff4566108d0.png)

**Comment by xsticcydev** [comment]
Thanks for the report!
I fixed this now!
